#+OPTIONS: ':nil *:t -:t ::t <:nil H:6 \n:nil ^:nil arch:headline author:t
#+OPTIONS: c:nil creator:nil d:(not "LOGBOOK") date:t e:t email:nil f:t
#+OPTIONS: inline:t num:t p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+OPTIONS: timestamp:t title:t toc:t todo:t |:t
#+TITLE: README
#+DATE: <2015-10-09 周五>
#+AUTHOR:
#+EMAIL:
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 24.5.1 (Org mode 8.3.2)

* 目录                                                                 :TOC:
 - [[#特点][特点]]
 - [[#安装][安装]]
 - [[#设置中英文等宽字体][设置中英文等宽字体]]
   - [[#方法一：][方法一：]]
   - [[#方法二：][方法二：]]
   - [[#说明][说明]]
 - [[#中英文混排时的line-wrap][中英文混排时的line wrap]]
 - [[#keybindings][Keybindings]]

* 特点
这个private layer作为spacemacs官方[[https://github.com/syl20bnr/spacemacs/tree/master/layers/chinese][Chinese layer]]的一个替代， *大部份设置都与Chinese layer相同，在它的基础上做了少量修改。* 之所以另外开一个layer，主要是因为官方的layer还不能完全满足我个人的需要。本设置层整合了ELPA中和中文写作有关的包，目的是为使用spacemacs进行中文写作的同学提供帮助，节省大家的时间。其中包含了以下和中文写作有关的包：

- ace-pinyin :: 根据汉字的拼音首字母进行ace-jump。
- chinese-pyim :: 目前最好用的emacs拼音输入法。
- find-by-pinyin-dired :: 根据拼音首字母找到并打开文件。
- pangu-spacing :: 以“软空格”的形式在中英混排文档中自动增加汉字与英文单词的间距。
- pinyin-search :: 顾名思义，根据汉字拼音首字母进行查找。(not activated by default)
- youdao-dictionary :: 有道词典
- visual-fill-column :: 处理中英文混排时的断句（visual fill）

和Chinese layer的不同之处主要有三点：

- pangu-spacing默认关闭，并且默认使用软空格
- 加入visual-fill-column处理中英文混排时的visual-line断句（代替adaptive-wrap）
- 定义了一些keybindings

* 安装
安装非常简单，首先

#+begin_src bash :export yes
git clone https://github.com/et2010/Han.git ~/.emacs.d/private/han
#+end_src

*注意：在没有官方Chinese layer之前，这个layer就叫Chinese，之后为了避免冲突，我将它改名为han。*

然后在你的.spacemacs文件中添加han设置层。配置类型推荐选择hybrid：

#+begin_src emacs-lisp :export yes
(defun dotspacemacs/layers ()
  (setq-default
   dotspacemacs-configuration-layers
   '(
     (han :variables
          han-enable-youdao-dict t)
     ))
  )

(defun dotspacemacs/init ()
  (setq-default
   dotspacemacs-editing-style 'hybrid)
  )
#+end_src

* 设置中英文等宽字体
** 方法一：
在 =.spacemacs= 文件中添加以下设置：
#+BEGIN_SRC emacs-lisp :export yes
  (defun dotspacemacs/user-config ()
    (spacemacs//set-monospaced-font "Source Code Pro" "Hiragino Sans GB W3" 14 16))
#+END_SRC

** 方法二：
如果使用方法一汉字出现乱码，则可以采用方法二。在 =.spacemacs= 中添加以下代码来配置中文字体：
#+BEGIN_SRC emacs-lisp :export yes
  (defun dotspacemacs/user-config ()
    (set-fontset-font "fontset-default"
                      ;; "CJK Unified Ideographs" (han) U+4E00 - U+9FFF
                      (cons (decode-char 'ucs #x4e00)
                            (decode-char 'ucs #x9fff))
                      "-*-Adobe Song Std-*-*-*-*-16-*-*-*-*-*-*-*"))
;;                          字体族名             字号
#+END_SRC
英文字体用spacemacs自带函数配置。
** 说明
当使用GUI的emacs时，默认的中文字符宽度一般不等于英文字符宽度的两倍，这样会导致用字符画的表格非常丑。解决办法是分别采用不同字号（高度）的中英文字体，使中文字符的宽度刚好等于英文字符宽度的两倍。通过试验发现不少常用的英文等宽字体字号设为14，中文字号设为16时可以满足等宽要求。字号这样配置时，以下列出的中英字体任意组合都可以满足等宽：

- 中文字体
  - *Adobe Fangsong Std*
  - Adobe Heiti Std
  - Adobe Kaiti Std
  - *Adobe Song Std*
  - *Hiragino Sans GB W3*
  - *NSimSun*
  - WenQuanYi Micro Hei Mono
  - WenQuanYi Zen Hei Mono
  - *微软雅黑*

- 英文字体（14号)
  - *Anonymous Pro*
  - *Bitstream Vera Sans Mono*
  - BPmono
  - *Consolas*
  - Courier 10 Pitch
  - /Courier New/
  - Cousine
  - *DejaVu Sans Mono*
  - Droid Sans Mono
  - *Envy Code R*
  - /FreeMono/
  - Liberation Mono
  - *Monaco*
  - MonospaceTypewriter
  - /Nimbus Mono L/
  - NotCourierSans
  - *Oxygen Mono*
  - *Source Code Pro*
  - /TlwgMono/

- 英文字体（16号）
  - Audimat Mono
  - *Inconsolata*
  - monofur
  - *Ubuntu Mono*

- 英文字体（12号）
  - /Linux Libertine Mono O/

注意：
1. *加粗字体* 为推荐使用字体， /斜体/ 为英文衬线字体。
2. 中文的16号字体可以与英文的16,14,12号字体实现等宽；大部分可以实现与中文16号字体等宽的英文等宽字体都是14号。（不推荐使用英文12号字体，即Linux Libertine Mono O，因为与中文字体高度相差太大）。
3. 不同系统中显示的字体族名不同，比如Adobe宋体，在Linux中显示为"Adobe Song Std", 在Windows中显示为"Adobe 宋体 Std L". 以上字体是在不同操作系统中试验得到的， *具体使用时以你的操作系统中所显示的字体族名为准。*
* TODO 中英文混排时的line wrap

* TODO Keybindings
可以在你的.spacemacs文件中添加以下设置：
#+BEGIN_SRC emacs-lisp :export yes
(defun dotspacemacs/user-config ()
  (define-key evil-hybrid-state-map (kbd "C-SPC") 'toggle-input-method)
  (define-key evil-hybrid-state-map (kbd "M-f") 'pyim-forward-word)
  (define-key evil-hybrid-state-map (kbd "M-b") 'pyim-backward-word)
  (define-key evil-hybrid-state-map (kbd "C-s") 'isearch-forward-pinyin)
  (define-key evil-hybrid-state-map (kbd "C-r") 'isearch-backward-pinyin)
  )
#+END_SRC
| key       | function                           | state  |
|-----------+------------------------------------+--------|
| ~SPC d~   | ace-pinyin-dwim                    | normal |
| ~SPC o d~ | find-by-pinyin-dired               | normal |
| ~SPC o y~ | youdao-dictionary-search-at-point+ | normal |
| ~C-SPC~   | toggle-input-method                | hybrid |
| ~M-f~     | pyim-forward-word                  | hybrid |
| ~M-b~     | pyim-backward-word                 | hybrid |
| ~C-s~     | isearch-forward-pinyin             | hybrid |
| ~C-r~     | isearch-backward-pinyin            | hybrid |
